# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee143b4092c0151ba9221c206e1d0acc558c9583e57c56dc61c81d071051e74e648b6dc82e93b7303a3e056c6559982004001f5a935cf5f56d7b0c41acb12e5a

test:
  secret_key_base: ce3694b696909ea89d453fd5d9d2cff1998c8a4fd8d5a525316744c47062ac85cafd9b325ae48c6ed4dd55ad5893980859404de01be4de5a6a783bd7887321f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
